# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 133eda71450a647a45ab2ee589a6ca1960fb0fb8c4d26ad873ea4bb6a4feb2dad49d9b793700b33ad19d250a4a39d9f871d6b141035bddc06b33619297d5f81b

test:
  secret_key_base: 6cfedb391288c1051ecf14f05db3941ee770f5b1178c5d712d1a19fc05c19f6b974027dc206431a374bba656b3672fa5f0795b2fe5db196070f2e8df3e36498f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
